# Generated by Django 4.1.3 on 2024-06-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forgotten', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'Places'},
        ),
        migrations.AlterField(
            model_name='places',
            name='upload_picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
