# Generated by Django 4.1.3 on 2024-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forgotten', '0003_alter_category_options_alter_places_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
