# Generated by Django 4.1.3 on 2024-06-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forgotten', '0004_places_latitude_places_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='Forgotten.places'),
        ),
        migrations.AddField(
            model_name='places',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='places',
            name='uptime',
            field=models.DateTimeField(auto_now=True, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='places',
            name='upload_picture',
            field=models.ImageField(blank='True', null='True', upload_to='media/'),
        ),
    ]
